#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
web_root="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$web_root/.." && pwd)"
writing_root="$repo_root/writing"
output_file="$web_root/assets/data/writing-catalog.js"

python3 - "$writing_root" "$output_file" <<'PYTHON'
import json
import re
import sys
from datetime import datetime
from pathlib import Path


writing_root = Path(sys.argv[1])
output_file = Path(sys.argv[2])


def markdown_section(text: str, heading: str) -> str:
    pattern = rf"(?ms)^##\s+{re.escape(heading)}\s*\r?\n(.*?)(?=^##\s+|\Z)"
    match = re.search(pattern, text)
    return match.group(1).strip() if match else ""


catalog = []

for category_directory in sorted(writing_root.iterdir(), key=lambda path: path.name):
    if not category_directory.is_dir() or not re.match(r"^T[12]-\d{2}-", category_directory.name):
        continue

    task_part, _, category_name = category_directory.name.split("-", 2)
    essay_directory = category_directory / "essays"
    questions = []

    for question_file in sorted(category_directory.glob("*.md"), key=lambda path: path.name):
        question_id = question_file.stem
        question_text = question_file.read_text(encoding="utf-8")
        version_files = (
            sorted(essay_directory.glob(f"{question_id}-Essay-V*.md"), key=lambda path: path.name)
            if essay_directory.is_dir()
            else []
        )
        versions = []

        for version_file in version_files:
            version_text = version_file.read_text(encoding="utf-8")
            version_match = re.search(r"-V(\d+)$", version_file.stem)
            versions.append(
                {
                    "version": int(version_match.group(1)) if version_match else 0,
                    "filename": version_file.name,
                    "date": datetime.fromtimestamp(version_file.stat().st_mtime).strftime("%Y-%m-%d"),
                    "essay": markdown_section(version_text, "Essay"),
                    "thoughts": markdown_section(version_text, "My thoughts"),
                    "feedback": markdown_section(version_text, "ChatGPT feedback"),
                    "revision_notes": markdown_section(version_text, "Revision notes"),
                }
            )

        questions.append(
            {
                "id": question_id,
                "written": bool(version_files),
                "version_count": len(version_files),
                "instructions": markdown_section(question_text, "Instructions"),
                "versions": versions,
            }
        )

    catalog.append(
        {
            "key": category_directory.name,
            "task": int(task_part[1:]),
            "name": category_name,
            "total": len(questions),
            "written": sum(1 for question in questions if question["written"]),
            "questions": questions,
        }
    )

output_file.parent.mkdir(parents=True, exist_ok=True)
json_text = json.dumps(catalog, ensure_ascii=False, indent=2)
output_text = (
    "// Generated by 00-web/scripts/Build-WritingCatalog.ps1 or Build-WritingCatalog.sh.\n"
    "// Edit the source Markdown files under writing, then rebuild. "
    "Do not edit this generated data directly.\n"
    f"window.writingCatalog = {json_text};\n"
)
output_file.write_text(output_text, encoding="utf-8", newline="\n")
print(f"Generated {output_file}")
PYTHON
